### ISSUE TITLE
wrong expression construction for multi-variable functions

### ISSUE THREAD

**Issue by jaupe** [sliceup/sliceup-node#1]
The API doesn't construct multi-variable functions correctly so they never get evaluated in slicedb.

This affects all our binary and ternary functions in our API.

For example:

    sliceup.query({
        'select': [last('price')],
        'from': 'demo',
        'by': [bar('time, time(1,0,0))]
    })

This query doesn't work because `bar` is not constructed properly.

The `bar` function should construct the expression as:

`{'Bar': [{'Id':'time'}, {'Time':'01:00:00'}]}`

Thus, all args to a function that has more than one arg should be populated in an array.

Alas, the syntatic sugar for time series queries is not working yet:

https://runkit.com/sliceup/5d754641bbb8b6001b5b1753

**Comment by harzo** [comment]
Resolved in https://github.com/sliceup/sliceup-node/commit/c63240c4da7d820899566cfa25376fcc4738f80e
