### ISSUE TITLE
add functions to API

### ISSUE THREAD

**Issue by jaupe** [sliceup/sliceup-node#2]
Unary functions:

- [x] `date(y, m, d)` => `{'Date':  '1983/10/25'}` => date value
- [x] `bool(arg)` => `{'Bool': bool}` => boolean value
- [x] `alias(id, name)` => `{'ColAlias':[id, name]}` => rename a column
- [x] `datetime(y,mm,dd,h,m,s)` => `{'DateTime':'2009/10/25T09:00:13'}` => datetime value
- [x] `int(arg)` => `{'Int':arg}` => int value
- [x] `float(arg)` => `{'Float': arg}` => float value
    Int(i32),
- [x] `str(arg)` => `{'String': arg}` => string value
    Int(i32),
- [x] `max(arg)` => `{'Max': arg}` =>  highest value
- [x] `min(arg)` => `{'Min': arg}` => lowest value
- [x] `avg(arg)` => `{'Avg': arg}` => arithemetic mean
- [x] `sum(arg)` => `{'Sum': arg}` => summation
- [x] `sums(arg)` => `{'Sums': arg}` => the rolling cumulative sum
- [x] `var(arg)` => `{'Var': arg}` => the variance
- [x] `dev(arg)` => `{'Dev': arg}` => the standard deviation
- [x] `unique(arg)` => `{'Unique': arg}` => all unique values  
- [x] `year(arg)` => `{'Year': arg}` => year constituent of a date
- [x] `month(arg)` => `{'Month': arg}` => month constituent of a date
- [x] `last(arg)` => `{'Last': arg}` => last element
- [x] `count(arg)` => `{'Count': arg}` => the number of elements in a value

Binary Functions

- [x] `bar(lhs, rhs)` => `{'Bar': arg}` => bars values into buckets for aggregation
- [x] `eq(lhs, rhs)` => `{'Eq': arg}` => equality
- [x] `neq(lhs, rhs)` => `{'Neq': arg}` => negated equality
- [x] `gt(lhs, rhs)` => `{'Gt': arg}` => negated equality
- [x] `lt(lhs, rhs)` => `{'Lt': arg}` => less than equality
- [x] `lte(lhs, rhs)` => `{'Lte': arg}` => less than or equals to equality
- [x] `gte(lhs, rhs)` => `{'Gte': arg}` => greater than or equals to equality
- [x] `add(lhs, rhs)` => `{'Add': arg}` => vectorised addition
- [x] `sub(lhs, rhs)` => `{'Sub': arg}` => vectorised subtraction
- [x] `mul(lhs, rhs)` => `{'Mul': arg}` => vectorised multiplication
- [x] `div(lhs, rhs)` => `{'Div': arg}` => vectorised division
- [x] `ema(id, alpa)` => `{'Div': arg}` => exponential moving average. alpha is the decay parameter
- [x] `mavg(id, lookback)` => `{'Div': arg}` => moving average. lookback is the number of points to lookback from
- [x] `mdev(id, lookback)` => `{'Div': arg}` => moving standard deviation. lookback is the number of points to lookback from

**Comment by harzo** [comment]
@jaupe Please review [functions.js](https://github.com/sliceup/sliceup-node/blob/master/functions.js) file to confirm that all functions are correctly implemented.
